services:

  echo-agent:
    build:
      context: ./echo
    image: smith-echo-agent
    container_name: smith-echo-agent
    ports:
      - "8001:8080"
    environment:
      - ACP_HOST=0.0.0.0
      - ACP_PORT=8080

  codex-agent:
    build:
      context: ./codex
    image: smith-codex-agent
    container_name: smith-codex-agent
    ports:
      - "8002:8080"
    environment:
      - CODEX_ACP_VERSION=0.3.9
      - LOG_LEVEL=DEBUG
