services:
  echo-agent:
    build:
      context: ./echo
    image: smith-echo-agent
    container_name: smith-echo-agent
    ports:
      - "8001:8080"
    environment:
      - ACP_HOST=0.0.0.0
      - ACP_PORT=8080
